mysite/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommned/', views.recommend, name="recommend"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail

# Create your models here.
def articles_image_path(instance, filename):
    return f'user_{instance.user.pk}/{filename}'

class Article(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    # blank = 유효성 검사시
    # null = DB 상의 컬럼의 Null
    # image = models.ImageField(blank=True, upload_to="%y/%m/%d/")
    image = models.ImageField(blank=True, upload_to=articles_image_path)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200,300)],
        format='JPEG',
        options={'quality':90}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles',
        blank=True
    )
    recommend = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="recommend_articles",
        blank=True
    )

    def __str__(self):
        return f'{self.pk}번째 글, {self.title}-{self.content}'

class Comment(models.Model):
    # 멤버 변수 = models.외래키(참조하는 객체, 삭제 되었을 때 처리 방법)
    article = models.ForeignKey(Article, on_delete=models.CASCADE) #, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 역참조 값 설정 related_name='comments'
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Article:{self.article}, {self.pk}-{self.content}'

mysite/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ['user','like_users', 'recommend']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        # fields = ['content']
        exclude = ['article','user']

mysite/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
# DVDH
# django가 주는 views에서 쓸 decorators http를 위한
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib import messages
from django.urls import resolve
from django.core.paginator import Paginator
from django.http import JsonResponse

# Create your views here.
def index(request):
    articles = Article.objects.all()
    # 1. Paginator(전체 리스트, 한 페이지당 개수)
    paginator = Paginator(articles, 3)
    # 2. 몇 번째 페이지를 보여줄 것인지 GET으로 받기
    # 'articles/?page=3'
    page = request.GET.get('page')
    # 해당하는 페이지의 게시글만 가져오기
    articles = paginator.get_page(page)
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    # 1은 N을 보장할 수 없기 때문에 querySet(comment_set)형태로 조회 해야한다.
    comments = article.comment_set.all()
    # comment = Comment.objects.filter(article=article)
    context = {
        'article': article,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'articles/detail.html', context)

@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            messages.success(request, '글이 생성되었습니다.')
            return redirect('articles:detail', article.pk)
        else:
            messages.error(request, '글 생성 실패')
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == "POST":
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form
        }
    else:
        return redirect('articles:detail', article.pk)
    return render(request, 'articles/form.html', context)

@login_required
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == "POST":
            article.delete()
            return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)
    return redirect('articles:detail', article.pk)

@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        # if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            # comment_article_id = article.pk
            comment.user = request.user
            comment.save()
            return redirect('articles:detail', article.pk)
        else:
            # comment_form = CommentForm()
            context = {
                'comment_form' : comment_form,
                'article' : article
            }
        return render(request, 'articles/detail.html', context)
    else:
        return redirect('accounts:login')


@require_POST
def comment_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        # comment = Comment.objects.get(pk=comment_pk)
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            # if request.method == "POST": @require_POST 사용하므로 필요 없음
            comment.delete()
            return redirect('articles:detail', article_pk)
        else:
            return redirect('articles:detail', article_pk)
    else:
        return redirect('accounts:login')

@login_required
def like(request, article_pk):
    # 특정 게시물에 대한 정보
    article = get_object_or_404(Article, pk=article_pk)
    # 좋아요를 누른 유저에 대한 정보
    user = request.user
    # 사용자가 게시글의 좋아요 목록에 있으면
    if user in article.like_users.all():
        article.like_users.remove(user)
        liked = False
    else:
        article.like_users.add(user)
        liked = True
    context = {
        'liked': liked,
        'count': article.like_users.count()
    }
    return JsonResponse(context)

@login_required
def recommend(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if user in article.recommend.all():
        article.recommend.remove(user)
    else:
        article.recommend.add(user)
    return redirect('articles:index')

mysite/articles/templates/articles/_like.html
{% if user in article.like_users.all %}
  <i class="fas fa-heart fa-lg like-button" data-id="{{ article.id }}" style="color: crimson;"></i>
 {% else %}
  <i class="far fa-heart fa-lg like-button" data-id="{{ article.id }}" style="color: black;"></i>
 {% endif %}
 <span id="like-count-{{ article.pk }}">좋아요 수 : {{ article.like_users.all|length }}</span>
 <br>
 {% if user in article.recommend.all %}
  <a href="{% url 'articles:recommend' article.pk %}">
    추천 취소
  </a>
 {% else %}
  <a href="{% url 'articles:recommend' article.pk %}">
    추천
  </a>
 {% endif %}
 추천  수 : {{ article.recommend.all|length }}
 <br>

mysite/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<h1>상세 페이지</h1>
<hr>
<p>{{ article.pk }}번째 글</p>
<h2>{{ article.title }}</h2>
<h3>{{ article.content }}</h3>
{% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}">
  <img src="{{ article.image_thumbnail.url }}" alt="{{ article.image }}">
{% endif %}
<hr>
<p>{{ comments|length }}개의 댓글</p>
<!-- <p>{{ article.comment_set.all|length }}</p> -->
<ul>
  {% for comment in comments %}
  <li>
    {{ comment.content }} - 작성자 : {{ comment.user.username }}
    {% if comment.user == user %}
                                          <!-- 2개 이상의 값을 넘겨주고자 할 때 순서 주의 -->
    <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST"> 
      {% csrf_token %} 
      <input type="submit" value="댓글삭제">
    </form>
    {% endif %}
  </li>
  {% empty %}
    <p>댓글이 없습니다.</p>
  {% endfor %}
  {% include 'articles/_like.html' %}
</ul>
<hr>
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {{ comment_form }}
  <input type="submit" value="댓글생성">
</form>
<hr>
<a href="{% url 'articles:index' %}">[back]</a>
{% if article.user == user %}
  <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE" class="btn btn-primary">
  </form>
{% endif %}

<script src="{% static 'articles/js/like.js' %}"></script>
{% endblock %}

mysite/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
  <h1>글 생성</h1>
{% else %}
  <h1>글 수정</h1>
{% endif %}

<hr>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

  <a href="{% url 'articles:index' %}">[BACK]</a>

{% endblock %}

mysite/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<h1>메인 페이지 입니다.</h1>
<hr>
<a href="{% url 'articles:create' %}" class="btn btn-primary">[CREATE]</a>
<hr>
{% for article in articles %}
 <p>{{ article.pk }}번째 글</p>
 <p>작성자 : {{ article.user.username }}</p>
 <p>{{ article.title }}</p>
 <p>댓글 개수 : {{ article.comment_set.all|length }}</p>
 <!-- {% if user in article.like_users.all %}
  <a href="{% url 'articles:like' article.pk %}">
    <i class="far fa-heart fa-lg text-danger"></i>
  </a>
 {% else %}
  <a href="{% url 'articles:like' article.pk %}">
    <i class="fas fa-heart fa-lg text-danger"></i>
  </a>
 {% endif %}
 좋아요 수 : {{ article.like_users.all|length }}
 <br>
 {% if user in article.recommend.all %}
  <a href="{% url 'articles:recommend' article.pk %}">
    추천 취소
  </a>
 {% else %}
  <a href="{% url 'articles:recommend' article.pk %}">
    추천
  </a>
 {% endif %}
 추천  수 : {{ article.recommend.all|length }}
 <br> -->
 {% include 'articles/_like.html' %}
 <a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a>
 <hr>
{% endfor %}
{% for num in articles.paginator.page_range %}
<a href="{% url 'articles:index' %}?page={{ num }}">{{ num }}</a>
{% endfor %}

  <script src="{% static 'articles/js/like.js' %}"></script>
{% endblock %}