mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="followings",
        blank=True
    )
    # 각족 필드들 추가
    # createsuperuser 불가 따라서 필드 추가하기 전에 admin 계정 만드는 것이 좋다.
    # shell_plus
    # create_user is_staff, is_superuser True

mysite/articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail

# Create your models here.
def articles_image_path(instance, filename):
    return f'user_{instance.user.pk}/{filename}'

class Article(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    # blank = 유효성 검사시
    # null = DB 상의 컬럼의 Null
    # image = models.ImageField(blank=True, upload_to="%y/%m/%d/")
    image = models.ImageField(blank=True, upload_to=articles_image_path)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200,300)],
        format='JPEG',
        options={'quality':90}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles',
        blank=True
    )
    recommend = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="recommend_articles",
        blank=True
    )

    def __str__(self):
        return f'{self.pk}번째 글, {self.title}-{self.content}'

class Comment(models.Model):
    # 멤버 변수 = models.외래키(참조하는 객체, 삭제 되었을 때 처리 방법)
    article = models.ForeignKey(Article, on_delete=models.CASCADE) #, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 역참조 값 설정 related_name='comments'
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Article:{self.article}, {self.pk}-{self.content}'

mysite/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name']

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        # fields = 

mysite/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        # AuthenticationForm 은 ModelForm이 아닌 Form 상속
        # 별도로 정의된 Model이 없다는 뜻
        # 그래서 넘겨주는 인자가 달라진다.
        if form.is_valid():
            # 로그인은 DB에 뭔가 작성하는 것은 동일하지만, 연결된 모델이 있는건 아니다.
            # 그럼 무엇을 확인해야 하는가?
            # 세션과 유저 정보
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@require_POST
def delete(request):
    request.user.delete()
    return redirect('articles:index')

def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # 기존 세션 유지
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person
    }
    return render(request, 'accounts/profile.html', context)

def follow(request, user_pk):
    # person에 담긴 user_pk값을 가진 유저는 프로필의 주인이다.
    # request.user는 나. 요청을 보내온 사용자이다.
    person = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('accounts:profile', person.username)

mysite/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form pass_form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

{% endblock %}

mysite/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
  <h1>회원 가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
  <h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
  <h1>회원정보 수정</h1>
{% elif request.resolver_match.url_name == 'change_password' %}
  <h1>비밀번호 변경</h1>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      submit
    </button>
  {% endbuttons %}
</form>

{% endblock %}

mysite/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form login_form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      로그인
    </button>
  {% endbuttons %}
</form>

{% endblock %}

mysite/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
<h1>{{ person.username }} {{ person.pk }}</h1>
<!-- 팔로우 로직 구현 -->
{% if user != person %}<!-- 본인일때는 팔로우 안보이도록 -->
{% if user in person.followers.all %}
<a href="{% url 'accounts:follow' person.pk %}">팔로우 취소</a>
{% else %}
<a href="{% url 'accounts:follow' person.pk %}">팔로우</a>
{% endif %}
{% endif %}
<!-- 유저가 작성한 모든 게시물 -->
<p>유저가 작성한 게시글들</p>
<ul>
  {% for article in person.article_set.all %}
    <li>{{ article.title }}</li>
    <li>{{ article.content }}</li>
  {% endfor %}
</ul>

<!-- 유저가 작성한 모든 댓글 -->
<p>유저가 작성한 댓글들</p>
<ul>
  {% for comment in person.comment_set.all %}
    <li>{{ comment.content }}</li>
  {% empty %}
    <p>댓글이 없습니다.</p>
  {% endfor %}
</ul>

<!-- 유저가 좋아요 누른 게시글 -->
<p>유저가 좋아요 누른 게시글</p>
<ul>
  {% for like in person.like_articles.all %}
    <li>{{ like.title }}</li>
  {% empty %}
    <p>좋아요 누글 게시글이 없습니다.</p>
  {% endfor %}
</ul>
{% endblock %}

mysite/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

{% endblock %}

mysite/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form update_form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

{% endblock %}