mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/fd5cc6fe1b.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message.message }}
      </div>
    {% endfor %}
  {% endif %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'accounts:profile' user.username %}">{{ user.username }}</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <!-- a 태그는 GET 방식 -->
        <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">[Logout] <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link text-white" href="{% url 'accounts:update' %}">[회원정보 수정]</a>
        <a class="nav-item nav-link text-white" href="{% url 'accounts:update' %}">[비밀번호 변경]</a>
        <form action="{% url 'accounts:delete' %}" method="POST" class="nav-item nav-link text=white" tabindex="-1" aria-disabled="true">
          {% csrf_token %}
          <input type="submit" value="회원 탈퇴">
        </form>
        {% else %}
        <a class="nav-item nav-link text-white" href="{% url 'accounts:login' %}">[Login]</a>
        <a class="nav-item nav-link text-white" href="{% url 'accounts:signup' %}">[Signup]</a>
        {% endif %}
      </div>
    </div>
  </nav>
  <div class="container">
    <!-- <div style="float: right;">
      <h1>{{ user.username }}</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
        <a href="{% url 'accounts:update' %}">[회원정보 수정]</a>
        <a href="{% url 'accounts:change_password' %}">[비밀번호 변경]</a>
        <form action="{% url 'accounts:delete' %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="회원 탈퇴">
        </form>
      {% else %}
        <a href="{% url 'accounts:login' %}">[로그인]</a>
        <a href="{% url 'accounts:signup' %}">[회원가입]</a>
      {% endif %}
    </div> -->
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>
</html>